apply plugin: 'com.android.application'

android {
    namespace 'com.raxmonov.tarix7'
    compileSdk 34

    defaultConfig {
        applicationId "com.raxmonov.tarix7"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    signingConfigs {
        debug {
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
